### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by ryankurte** [dist-svc/dsf-daemon#8]
Requires an implementation of windows unix datagram sockets, ideally in async_std, see:

- https://github.com/Azure/tokio-uds-windows
- https://github.com/rust-lang/rust/issues/56533

Once this is implemented it can be re-added to the build matrix:
```yaml
          - target: i686-pc-windows-msvc
            os: windows-latest
            output: dsfd.exe
            use_cross: false
            experimental: true
```
